"""Add visibility flags to projects and reviews

Revision ID: 3080b741a877
Revises: 
Create Date: 2025-04-27 17:57:29.620923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3080b741a877'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_visible', sa.Boolean(), nullable=True))
    op.add_column('reviews', sa.Column('is_visible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'is_visible')
    op.drop_column('projects', 'is_visible')
    # ### end Alembic commands ###
