"""Add indexes to public visibility columns

Revision ID: 569433338482
Revises: 0d41d2392938
Create Date: 2026-02-10 19:49:19.195376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '569433338482'
down_revision: Union[str, None] = '0d41d2392938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_experiences_is_visible'), 'experiences', ['is_visible'], unique=False)
    op.create_index(op.f('ix_project_categories_is_visible'), 'project_categories', ['is_visible'], unique=False)
    op.create_index(op.f('ix_projects_is_visible'), 'projects', ['is_visible'], unique=False)
    op.create_index(op.f('ix_reviews_is_visible'), 'reviews', ['is_visible'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_is_visible'), table_name='reviews')
    op.drop_index(op.f('ix_projects_is_visible'), table_name='projects')
    op.drop_index(op.f('ix_project_categories_is_visible'), table_name='project_categories')
    op.drop_index(op.f('ix_experiences_is_visible'), table_name='experiences')
    # ### end Alembic commands ###
