"""Updated user model with featured skills

Revision ID: a606c6fa43eb
Revises: 166d156e9c7d
Create Date: 2025-05-07 19:15:43.278881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a606c6fa43eb'
down_revision: Union[str, None] = '166d156e9c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('featured_skill_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'featured_skill_ids')
    # ### end Alembic commands ###
