"""Add project category id to project table

Revision ID: c2e94408a301
Revises: b1dd2a87761f
Create Date: 2025-10-05 19:16:46.773777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2e94408a301'
down_revision: Union[str, None] = 'b1dd2a87761f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'projects', 'project_categories', ['project_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'project_category_id')
    # ### end Alembic commands ###
